export const categories = {
  "Famosos Argentina": [
    "Mirtha Legrand",
    "Susana Giménez",
    "Marcelo Tinelli",
    "Ricardo Darín",
    "Lionel Messi",
    "Diego Maradona",
    "Charly García",
    "Fito Páez",
    "Jorge Luis Borges",
    "Guillermo Francella",
  ],
  "Películas": [
    "Titanic",
    "El Padrino",
    "Star Wars",
    "Jurassic Park",
    "Harry Potter",
    "El Señor de los Anillos",
    "Pulp Fiction",
    "Forrest Gump",
    "Volver al Futuro",
    "El Rey León",
  ],
  "Famosos Mundial": [
    "Michael Jackson",
    "Madonna",
    "Queen Elizabeth II",
    "Leonardo DiCaprio",
    "Albert Einstein",
    "Tom Hanks",
    "Beyoncé",
    "Cristiano Ronaldo",
    "Taylor Swift",
    "Elon Musk",
  ],
  "Música": [
    "Queen",
    "The Beatles",
    "Soda Stereo",
    "Coldplay",
    "Dua Lipa",
    "Bad Bunny",
    "Led Zeppelin",
    "Pink Floyd",
    "Daft Punk",
    "Shakira",
  ],
  "Países": [
    "Argentina",
    "Brasil",
    "Japón",
    "Egipto",
    "Italia",
    "Australia",
    "Canadá",
    "Rusia",
    "Sudáfrica",
    "México",
  ],
};

export type Category = keyof typeof categories;
