export type KnownPerson = {
  name: string;
  avatar: string; // This will now be the filename, e.g., "dylan_rodriguez.png"
};

export const categories = {
  "Famosos Argentina": [
    "Mirtha Legrand", "Susana Giménez", "Marcelo Tinelli", "Ricardo Darín", "Lionel Messi",
    "Luck Ra", "La Joaqui", "Migue Granados", "Nico Occhiato", "Fito Páez",
    "Jorge Luis Borges", "Guillermo Francella", "Bizarrap", "Duki", "Nicki Nicole",
    "Tini Stoessel", "Lali Espósito", "Emilia Mernes", "Trueno", "Tiago PZK",
    "Milo J", "María Becerra", "Wos", "Dillom", "Rusherking",
    "Nathy Peluso", "Cazzu", "Lit Killah", "Khea", "FMK",
    "Ángel de Brito", "Beto Casella", "Santiago del Moro", "Guido Kaczka", "Darío Barassi",
    "Iván de Pineda", "Pampita", "Zaira Nara", "Wanda Nara", "Lizy Tagliani",
    "Flor Vigna", "Julieta Poggio", "Marcos Ginocchio", "Nati Jota", "Momi Giardina",
    "Santi Maratea", "Fran Stoessel", "Tuli Acosta", "Luzu TV",
    "Manu Ginóbili", "Juan Martín del Potro", "Ángel Di María", "Julián Álvarez", "Dibu Martínez",
    "Rodrigo De Paul", "Alexis Mac Allister", "Enzo Fernández", "Lautaro Martínez", "Franco Colapinto",
    "Adolfo Cambiaso", "Luciana Aymar", "Gabriela Sabatini", "Kun Agüero", "Cholo Simeone",
    "Lionel Scaloni", "Papo MC", "Coscu", "Luquitas Rodriguez", "Germán Beder",
    "Roberto Galati", "Hasbulla (mención honorífica en redes)", "Moria Casán", "Graciela Alfano", "Carmen Barbieri",
    "Federico Bal", "Laurita Fernández", "Peter Lanzani", "Chino Darín", "Joaquín Furriel",
    "Rodrigo de la Serna", "Luisana Lopilato", "Dolores Fonzi", "Úrsula Corberó (vía Chino)", "Carla Peterson",
    "Griselda Siciliani", "Benjamín Vicuña", "Eugenia 'China' Suárez", "Nico Vázquez", "Gimena Accardi",
    "Luli Salazar", "Luciana Salazar", "Nicole Neumann", "Vero Lozano", "Yanina Latorre",
    "Diego Latorre", "Morena Beltrán", "Gastón Edul", "Ariel Rodriguez Palacios", "Donato de Santis",
    "Damián Betular", "Germán Martitegui", "Narda Lepes", "Maru Botana", "Jimena Monteverde",
    "Charly García", "Andrés Calamaro", "Indio Solari", "Gustavo Santaolalla", "Trueno",
    "Ca7riel", "Paco Amoroso", "Nafta", "Conociendo Rusia", "Bandalos Chinos",
    "El Mató a un Policía Motorizado", "Zoe Gotusso", "Dante Spinetta", "Louta", "Airbag"
  ],
  "Películas": [
    "Titanic", "El Padrino", "Star Wars", "Jurassic Park", "Harry Potter", 
    "El Señor de los Anillos", "Pulp Fiction", "Forrest Gump", "Volver al Futuro", "El Rey León",
    "Inception", "Matrix", "Gladiador", "Interestelar", "El Caballero de la Noche",
    "Avatar", "Terminator 2", "Toy Story", "Shrek", "Bastardos Sin Gloria",
    "El Club de la Pelea", "Parásitos", "El Viaje de Chihiro", "La La Land", "Mad Max: Furia en el Camino",
    "Joker", "Coco", "Spider-Man: Into the Spider-Verse", "Whiplash", "Ciudadano Kane",
    "Psicosis", "2001: Odisea del Espacio", "La Lista de Schindler", "Sueño de Fuga", "El Silencio de los Inocentes",
    "Rescatando al Soldado Ryan", "Se7en", "Goodfellas", "El Gran Hotel Budapest", "E.T. El Extraterrestre",
    "Tiburón", "Indiana Jones: Cazadores del Arca Perdida", "Alien: El Octavo Pasajero", "Blade Runner", "El Show de Truman",
    "Eterno Resplandor de una Mente sin Recuerdos", "Amélie", "La Vida es Bella", "Cinema Paradiso", "Los Siete Samuráis",
    "Roma", "El Laberinto del Fauno", "Amores Perros", "Relatos Salvajes", "El Secreto de sus Ojos",
    "Nueve Reinas", "Birdman", "Everything Everywhere All at Once", "Dune", "Oppenheimer",
    "Barbie", "Poor Things", "Kill Bill", "Django Desencadenado", "Reservoir Dogs",
    "El Gran Lebowski", "Fargo", "No Country for Old Men", "Arrival", "Sicario",
    "Prisoners", "Her", "Ex Machina", "Moonlight", "Green Book",
    "The Shape of Water", "Nomadland", "Coda", "Braveheart", "Apocalypse Now",
    "Taxi Driver", "Gran Torino", "Los Infiltrados", "Lobo de Wall Street", "Once Upon a Time in Hollywood",
    "La Naranja Mecánica", "El Resplandor", "Scarface", "Raging Bull", "The Prestige",
    "Memento", "Up", "WALL-E", "Buscando a Nemo", "Los Increíbles",
    "Ratatouille", "Ghostbusters", "Die Hard", "Rocky", "Top Gun: Maverick", "John Wick"
  ],
  "Famosos Mundial": [
    "Michael Jackson", "Madonna", "Queen Elizabeth II", "Leonardo DiCaprio", "Albert Einstein",
    "Tom Hanks", "Beyoncé", "Cristiano Ronaldo", "Taylor Swift", "Elon Musk",
    "Lionel Messi", "Brad Pitt", "Angelina Jolie", "Will Smith", "Oprah Winfrey",
    "Bill Gates", "Mark Zuckerberg", "Steve Jobs", "Barack Obama", "Nelson Mandela",
    "Marilyn Monroe", "Elvis Presley", "Audrey Hepburn", "Charlie Chaplin", "Pablo Picasso",
    "Vincent van Gogh", "Stephen Hawking", "Marie Curie", "Isaac Newton", "Charles Darwin",
    "Dalai Lama", "Pope Francis", "Malala Yousafzai", "Greta Thunberg", "Jeff Bezos",
    "Lady Gaga", "Justin Bieber", "Rihanna", "Drake", "Adele",
    "Robert Downey Jr.", "Scarlett Johansson", "Dwayne Johnson", "Tom Cruise", "Jennifer Aniston",
    "Meryl Streep", "Morgan Freeman", "Jackie Chan", "Bruce Lee", "Keanu Reeves",
    "Roger Federer", "Serena Williams", "LeBron James", "Michael Jordan", "Tiger Woods",
    "Usain Bolt", "Lewis Hamilton", "Muhammad Ali", "Pele", "Diego Maradona",
    "Kim Kardashian", "Kylie Jenner", "Kendall Jenner", "Selena Gomez", "Ariana Grande",
    "Zendaya", "Tom Holland", "Timothée Chalamet", "Billie Eilish", "Harry Styles",
    "Jennifer Lopez", "Shakira", "Sofia Vergara", "Penélope Cruz", "Salma Hayek",
    "Emma Watson", "Benedict Cumberbatch", "Ryan Reynolds", "Margot Robbie", "Cillian Murphy",
    "Pedro Pascal", "Bad Bunny", "Rosalía", "J Balvin", "Maluma",
    "Kate Middleton", "Prince William", "Meghan Markle", "Donald Trump", "Joe Biden",
    "Vladimir Putin", "Xi Jinping", "Narendra Modi", "Emma Stone", "Anne Hathaway",
    "David Beckham", "Victoria Beckham", "Gordon Ramsay", "Jamie Oliver", "MrBeast"
  ],
  "Músicos y bandas": [
    "Queen", "The Beatles", "Soda Stereo", "Coldplay", "Dua Lipa", 
    "Bad Bunny", "Led Zeppelin", "Pink Floyd", "Daft Punk", "Shakira",
    "Taylor Swift", "The Weeknd", "Harry Styles", "Billie Eilish", "Rosalía",
    "Bizarrap", "Olivia Rodrigo", "Drake", "Ed Sheeran", "Justin Bieber",
    "Miley Cyrus", "Beyoncé", "Rihanna", "Kendrick Lamar", "Arctic Monkeys",
    "Tame Impala", "Gorillaz", "Radiohead", "The Strokes", "Imagine Dragons",
    "Twenty One Pilots", "Post Malone", "Travis Scott", "SZA", "Doja Cat",
    "Lana Del Rey", "Karol G", "Feid", "J Balvin", "Maluma",
    "Rauw Alejandro", "C. Tangana", "Nathy Peluso", "Trueno", "Wos",
    "Duki", "Tini", "Lali Espósito", "Babasonicos", "Enjambre",
    "Zoé", "Los Mesoneros", "Cuarteto de Nos", "Mon Laferte", "Jorge Drexler",
    "Natalia Lafourcade", "Fito Páez", "Charly García", "Spinetta", "Muse",
    "The Killers", "Paramore", "Bring Me The Horizon", "Foo Fighters", "Red Hot Chili Peppers",
    "Metallica", "Guns N' Roses", "Nirvana", "The Rolling Stones", "David Bowie",
    "Michael Jackson", "Madonna", "Bruno Mars", "Adele", "Sam Smith",
    "Hozier", "Florence + The Machine", "Glass Animals", "MGMT", "Foster The People",
    "Empire of the Sun", "Justice", "Calvin Harris", "Avicii", "David Guetta",
    "Marshmello", "Fred again..", "Skrillex", "Disclosure", "Kaytranada",
    "Tyler, The Creator", "Frank Ocean", "A$AP Rocky", "Mac Miller", "Childish Gambino",
    "Lizzo", "Janelle Monáe", "Kali Uchis", "Peso Pluma", "Christian Nodal", "Grupo Frontera"
  ],
  "Países y Ciudades": [
    "Argentina", "Rosario", "Ushuaia", "Brasil", "Japón", 
    "Kioto", "España", "Madrid", "Barcelona", "Canadá", 
    "Toronto", "Vancouver", "México", "Guadalajara", "Francia", 
    "París", "Lyon", "Italia", "Roma", "Venecia", 
    "Australia", "Sídney", "Alemania", "Berlín", "Múnich", 
    "Colombia", "Medellín", "Bogotá", "Egipto", "El Cairo", 
    "Portugal", "Lisboa", "Oporto", "Chile", "Santiago",
    "Grecia", "Atenas", "Santorini", "Noruega", "Oslo",
    "Países Bajos", "Ámsterdam", "Róterdam", "Tailandia", "Bangkok",
    "Phuket", "Perú", "Lima", "Cusco", "Irlanda",
    "Dublín", "Corea del Sur", "Seúl", "Busan", "Sudáfrica",
    "Ciudad del Cabo", "Nueva Zelanda", "Auckland", "Suiza", "Zúrich",
    "Ginebra", "Turquía", "Estambul", "Marruecos", "Marrakech",
    "Uruguay", "Montevideo", "Punta del Este", "Bélgica", "Bruselas",
    "Brujas", "Croacia", "Dubrovnik", "Zagreb", "Vietnam",
    "Hanói", "Costa Rica", "San José", "Islandia", "Reikiavik",
    "Escocia", "Edimburgo", "Austria", "Viena", "Salzburgo",
    "República Checa", "Praga", "Polonia", "Varsovia", "Cracovia",
    "Malasia", "Kuala Lumpur", "Cuba", "La Habana", "Singapur",
    "Córdoba", "Mendoza", "Salta", "San Miguel de Tucumán", "Mar del Plata", 
    "Bariloche", "Posadas", "Resistencia", "Neuquén", "San Juan", 
    "San Salvador de Jujuy", "Santa Fe", "Corrientes", "Bahía Blanca", "La Plata"
  ],
  "Conocidos de Lucia": [
    { "name": "Dylan Rodriguez", "avatar": "dylan_rodriguez.png" },
    { "name": "Eze Raggio", "avatar": "eze_raggio.png" },
    { "name": "Javi Alberio", "avatar": "javi_alberio.png" },
    { "name": "Lucas Vasco", "avatar": "lucas_vasco.png" },
    { "name": "Marcos Corona", "avatar": "marcos_corona.png" },
    { "name": "Mauro Fredes", "avatar": "mauro_fredes.png" },
    { "name": "Nico Marenzi", "avatar": "nico_marenzi.png" },
    { "name": "Seba Gauto", "avatar": "seba_gauto.png" }
  ]
};

export type SecretWord = string | KnownPerson;
export type CategoryContent = string[] | KnownPerson[];

export type Category = keyof typeof categories;
